### ISSUE TITLE
Chrome Support

### ISSUE THREAD

**Issue by Dru-Go** [oslabs-beta/Realize#63]

**Comment by hmitrea** [comment]
Hi Dru-go, at the moment we're still pending approval from Chrome. We should get it shortly, apologizes for the inconvenience. Until then, the [Firefox](https://addons.mozilla.org/en-US/firefox/addon/realizeforreact/?src=search) extension works ok
Will let you know as soon as we get the approval.

**Comment by hmitrea** [comment]
**Available on [Chrome NOW](https://chrome.google.com/webstore/detail/realize-for-react/llondniabnmnappjekpflmgcikaiilmh?authuser=0&hl=en)**
